version: '3'
services:
  web:
    build: .
    ports: 
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost:80
      interval: 5s
      timeout: 25s
      retries: 10
      start_period: 10s