name: Build and test
run-name: Build and test triggered by ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  build:
    env:
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pylint
        run: pylint fastapi-test --output=pylintresult --output-format=parseable
        continue-on-error: true
      - name: Add pylint results to summary
        run:  |
          echo "| File | Code | Description |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          awk -F"[][{}]" 'match($0, /^.*\.py*/) {print "| " $1 " | " $2 " | " $3 " |"}' pylintresult
      - name: Run tests
        run: pytest fastapi-test --ctrf ctrf/pytest.json
      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t fastapi-test .
      - name: Run Docker Compose
        run: docker compose up -d --wait
      #- name: Run FastAPI
        #working-directory: ./fastapi-test
        #run: fastapi dev &
      - name: Smoketest
        run: curl http://127.0.0.1:8080
      - uses: actions/setup-node@v2
      - name: Install newman
        run:  npm install -g newman newman-reporter-htmlextra newman-reporter-ctrf-json
      - name: Run Postman Tests
        run: newman run ./postman/fastapi-test.postman_collection.json -r "cli,junit,htmlextra,ctrf-json"
      - name: Archive Postman test results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: newman/
      - name: Publish CTRF results
        run: |
          npx merge-ctrf ./ctrf --output merged-ctrf.json
          npx github-actions-ctrf ./ctrf/merged-ctrf.json
        if: always()
      - name: Run coverage.py
        run: coverage run -m pytest fastapi-test
      - name: Add coverage to summary
        run:  |
          echo "# Code Coverage" >> $GITHUB_STEP_SUMMARY
          coverage report | awk '{if ($0 !~ /^-.*/) {print "| " $1 " | " $2 " | " $3 " | " $4 " |"} else {print "| --- |"}}' >> $GITHUB_STEP_SUMMARY
        
        
    
