name: Build and test
run-name: Build and test triggered by ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pylint
        run: pylint fastapi-test
        continue-on-error: true
      - name: Run tests
        run: pytest fastapi-test
      - name: Run FastAPI
        working-directory: ./fastapi-test
        run: fastapi dev &
      - name: Smoketest
        run: curl http://127.0.0.1:8000
      - uses: actions/setup-node@v2
      - name: Run Postman Tests
        run: | 
          npm install newman
          npm install newman-reporter-htmlextra
          newman run ./postman/fastapi-test.postman_collection.json -r "cli,junit,htmlextra"
      - name: Archive Postman test results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: newman/
      - name: Publish Postman test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: newman/*.xml
        
    
