name: Build and test
run-name: Build and test triggered by ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.3'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest fastapi-test
    
