name: Build and test
run-name: Build and test triggered by ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pylint
        run: pylint fastapi-test
        continue-on-error: true
      - name: Run tests
        run: pytest fastapi-test --ctrf ctrf/pytest.json
      - name: Run FastAPI
        working-directory: ./fastapi-test
        run: fastapi dev &
      - name: Smoketest
        run: curl http://127.0.0.1:8000
      - uses: actions/setup-node@v2
      - name: Install newman
        run:  npm install -g newman 
      - name: Install html reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Install ctrf reporter
        run: npm install -g newman-reporter-ctrf-json
      - name: Run Postman Tests
        run: newman run ./postman/fastapi-test.postman_collection.json -r "cli,junit,htmlextra,ctrf-json"
      - name: Archive Postman test results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: newman/
      - name: Publish CTRF results
        run: |
          npx merge-ctrf ./ctrf --output merged-ctrf.json
          npx github-actions-ctrf ./ctrf/merged-ctrf.json
        if: always()
        
        
    
